#!/bin/bash

cp /var/log/apt/history.log /home/catinbetween/apt_history/test/;


for file in $( find /var/log/apt/ -type f -name 'history.log.*.gz' ); do
	echo $file;
	base=`basename ${file%.gz}`
	sudo gzip -dk $file -c > /home/catinbetween/apt_history/test/$base;
done

if [[ ! $(touch /home/catinbetween/apt_history/test/out.txt) ]]; then
	rm /home/catinbetween/apt_history/test/out.txt;
	touch /home/catinbetween/apt_history/test/out.txt
fi


# cat history.log.4 | grep 'apt-get install ' >> log2.txt

for file in $( find /home/catinbetween/apt_history/test/ -type f -name 'history*' ); do 
	
	#printf "\nfile $i :\n\n" >> /home/catinbetween/apt_history/test/out.txt
	
	packages=`grep -oP  '((?<=apt install)|(?<=apt-get install))(.*$)' -- $file | grep -vP '(--)'`
	
	#echo $cat_1
	
	for package in $(echo $packages); do
		#echo $i;
		if [[ $(dpkg -s $package) && ! $(grep -Fxq "$package" /home/catinbetween/apt_history/test/out.txt) ]]; then
			#echo "not installed"
			echo $package >> /home/catinbetween/apt_history/test/out.txt
		fi;
	done
	rm $file;
	
	#cat_1=`grep -e 'apt install ' -- $i | `
	#cat_2=`grep -e 'apt-get install' -- $i | sed -r "( [a-Z]*$)"`
	
	#echo "$cat_1" >> /home/catinbetween/apt_history/test/out.txt
	#echo "$cat_2" >> /home/catinbetween/apt_history/test/out.txt
	
done;

#/((?:apt install)( .+$)/p
