#!/bin/bash

# copy most recent history
cp /var/log/apt/history.log /home/catinbetween/apt_history/test/;

# get older apt history logs and extract them to folder
for file in $( find /var/log/apt/ -type f -name 'history.log.*.gz' ); do
	echo $file;
	base=`basename ${file%.gz}`
	sudo gzip -dk $file -c > /home/catinbetween/apt_history/test/$base;
done

# if outfile exists, remove and create new one
if [[ ! $(touch /home/catinbetween/apt_history/test/out.txt) ]]; then
	rm /home/catinbetween/apt_history/test/out.txt;
	touch /home/catinbetween/apt_history/test/out.txt
fi

for file in $( find /home/catinbetween/apt_history/test/ -type f -name 'history*' ); do 
	
	# Filter all install instructions
	packages=`grep -oP  '((?<=apt install)|(?<=apt-get install))(.*$)' -- $file | grep -vP '(--)'`
	
	# check if package is installed and is not already in output file
	for package in $(echo $packages); do
		#echo $i;
		if [[ $(dpkg -s $package) && ! $(grep -Fxq "$package" /home/catinbetween/apt_history/test/out.txt) ]]; then
			#echo "not installed"
			echo $package >> /home/catinbetween/apt_history/test/out.txt
		fi;
	done
	
	# remove redundant copy
	rm $file;	
done;
